### ISSUE TITLE
Logo's alt text is not appropriate for its context

### ISSUE THREAD

**Issue by McSinyx** [httpjamesm/AnonymousOverflow#115]
https://github.com/httpjamesm/AnonymousOverflow/blob/3a508ddbd4f273f2f33d1f622db4b0e9f6284315/templates/home.html#L19-L26

An image of four circles next to the site's name would take guess work in order to understand.  IMHO a more appropriate alternative text representation for the logo should include the word _logo_, but [in this case the logo does not convey any information other than visual decoration so the alt text could also very well be empty](https://www.w3.org/WAI/tutorials/images/decorative).

**Comment by httpjamesm** [comment]
Please check #116 and let me know if that addresses this
