### ISSUE TITLE
Werid redirect result

### ISSUE THREAD

**Issue by freedit-dev** [httpjamesm/AnonymousOverflow#118]
https://askubuntu.com/questions/1507571/ubuntu-23-10-update-problems-some-index-files-failed-to-download

is redirected to 

https://code.whatever.social/questions/1507571/ubuntu-23-10-update-problems-some-index-files-failed-to-download

![image](https://github.com/httpjamesm/AnonymousOverflow/assets/107944572/eabd71ee-dc2d-4002-acc5-957959b84724)

**Comment by httpjamesm** [comment]
Are you sure this isn't an extension issue? I pasted the askubuntu URL into the homepage form and I was redirected just fine.

**Comment by httpjamesm** [comment]
It works for me... 
![image](https://github.com/httpjamesm/AnonymousOverflow/assets/51917118/aec3e25e-1740-4e24-8063-94d26974b7e1)

**Comment by httpjamesm** [comment]
> @httpjamesm The redirect URL is missing the domain string:
> 
> https://overflow.adminforge.de/exchange/opensource/questions/7397/restrict-gplv3-to-non-commercial-use has a link to https://overflow.adminforge.de/questions/5771/is-it-possible-to-restrict-gnu-gplv3-to-non-commercial-use-only, which is SO, not Opensource SE.
> 
> It's missing the `/exchange/opensource` bit.
> 
> Once you add it back, the link opens just fine: https://overflow.adminforge.de/exchange/opensource/questions/5771/is-it-possible-to-restrict-gnu-gplv3-to-non-commercial-use-only
> 
> Wouldn't it be easier and less bug-prone in general to standardise the URLs? Instead of SO being the default, it could be `/overflow`. Then we could easily have `/superuser`, `/askubuntu`, and `/exchange/X`, `/exchange/Y` as needed.

This is a different bug. This is an issue with links within questions.

**Comment by httpjamesm** [comment]
I think that should be a separate issue then?

**Comment by httpjamesm** [comment]
No. If you paste the askubuntu URL into the homepage form, it works just fine for me. I believe the issue you're encountering is specific to page links. Right now, the page links aren't using the same redirection logic.

**Comment by freedit-dev** [comment]
issue on the extension side: https://github.com/libredirect/browser_extension/issues/910

They have the same issue, but they just fixed it by removing askubuntu and superuser
