### ISSUE TITLE
Instances in a json file

### ISSUE THREAD

**Issue by ManeraKai** [httpjamesm/AnonymousOverflow#12]
We want to add AnonymousOverflow to [LibRedirect](https://github.com/libredirect/libredirect) ([issue](https://github.com/libredirect/libredirect/issues/577)), but can the instances be in a json file? Yes I can fetch them from the README, but it would be unreliable.

**Comment by httpjamesm** [comment]
Would a constantly updated json file in the repo work for you?

**Comment by ManeraKai** [comment]
Yep

**Comment by httpjamesm** [comment]
[Check out `instances.json`](https://github.com/httpjamesm/AnonymousOverflow/blob/main/instances.json)
