### ISSUE TITLE
Some comments not being parsed or displayed correctly

### ISSUE THREAD

**Issue by danielwerg** [httpjamesm/AnonymousOverflow#127]
Sometimes most valuable stuff is in question or one of the answers comments.

**Comment by httpjamesm** [comment]
Already implemented.

**Comment by danielwerg** [comment]
@httpjamesm
https://code.whatever.social/questions/4108313/how-do-i-find-the-length-of-an-array
https://stackoverflow.com/a/72769941/12038199
See answer that starts with "here you go". It has 1 comment.
