### ISSUE TITLE
Seeing "Error: You have exceeded the request limit. Please try again in a minute."

### ISSUE THREAD

**Issue by r7l** [httpjamesm/AnonymousOverflow#20]
This error is showing up quite often. How does it come to that? Does that mean the instance is blocked or is it just me using one instance to much?

I wonder since i wouldn't mind selfhosting an instance for me (can't run a public instance currently) but if this will hit my local instance as well, it wouldn't make much sense to do so.

**Comment by httpjamesm** [comment]
This is the built-in ratelimiter designed to prevent mass crawling and instance abuse. 

In the latest version, it has been increased and made more lenient. 

If you're on a shared IP address, it's possible that someone on your network is going through proxied pages too quickly. Another possibility is the instance is setup incorrectly for IP forwarding. 

Try visiting other instances if needed.

**Comment by r7l** [comment]
Fully understandable idea behind it. But it seems counterproductive for people who want to host for themselves.

I am not on a share IP but instead i am usually looking up stuff and open like 5 of the results from Google at once. For that reason i was actually thinking about about hosting myself anyways and even create and provide a package for Gentoo. SO having my IP in their logs is not my main concern but instead i like AO for stripping away all that JS crap and extra stuff that is slowing down browsers and drawing away attention. For that alone AO is an awesome application!

Would it be possible to have some option (preferable ENV variable) to disable this feature when hosting?

**Comment by httpjamesm** [comment]
Done, add `DISABLE_RATELIMIT = true` to your environment to disable it.

**Comment by r7l** [comment]
Awesome, thanks! Wasn't expecting it so quick. Will test and report back.

**Comment by r7l** [comment]
Finally found time to set everything up. Creating a package seems didn't work out as expect as template files are kinda bound to the working directory. But don't bother with it. Using your Docker images is probably fine for most of your users.

So far it works great with the setting. I've not seen any of these messages on my local instance so far. But i would like to make another suggestion:

The message reads `You have exceeded the request limit. Please try again in a minute.` and this is a misleading statement. Once blocked you can't use an instance for almost a day. It would probably be better to tell people to switch to other instances and maybe even link to the list.

**Comment by httpjamesm** [comment]
That is because it's a rolling ratelimit, which means the more you trigger it, the longer you're banned (https://github.com/httpjamesm/AnonymousOverflow/blob/bfa19bc2d283c59f21b1ee03048ca71def621b2c/src/middleware/ratelimit.go#L44).

**Comment by r7l** [comment]
Not sure if this works out well for users.

Using Libredirect, it randomly selects instances. I would even say it only has a single instance preselected. But i've changed the defaults so i can't say for sure.

For the reason of this random redirection people end up on some instances more then others. If you update this ratelimit everytime someone is randomly redirected to an instance, people would be required to manually disable the instance within the extension for the time being which would raise the bar for a ban on other instances as well. Later on they would most likely forget to enable instances again which would slim the randomness and also raise the overall ban level for them.

**Comment by httpjamesm** [comment]
No. The ratelimit is IP based, so if someone tries to abuse it, it'll only block their network.

**Comment by httpjamesm** [comment]
The ratelimit hasn't been an issue for me on any instances. It decrements the hashmap values for IP keys 60s after every request. You have to be flying through pages really quickly to trigger it, especially since static assets are now excluded.

**Comment by r7l** [comment]
Ok then. This is solved for me anyways by running my own instance. Thanks allot for adding this option.
