### ISSUE TITLE
[INSTANCE] New public instance

### ISSUE THREAD

**Issue by alx-alexpark** [httpjamesm/AnonymousOverflow#24]
Instance URL: ~~https://nitter.projectsegfau.lt/~~ https://overflow.projectsegfau.lt/
Region (Written Out - ex United States): (GeoDNS) United States/Luxembourg/India
Operated by (Link to your site): https://projectsegfau.lt

**Comment by alx-alexpark** [comment]
Individual instances:
https://overflow.eu.projectsegfau.lt/
https://overflow.us.projectsegfau.lt/
https://overflow.in.projectsegfau.lt/

**Comment by alx-alexpark** [comment]
I sent the wrong URL. It should have been https://overflow.projectsegfau.lt/

**Comment by httpjamesm** [comment]
Thanks for hosting an instance! It has been added to the README.

**Comment by alx-alexpark** [comment]
Thank You!
