### ISSUE TITLE
[INSTANCE] New public instance - overflow.projectsegfau.lt

### ISSUE THREAD

**Issue by gi-yt** [httpjamesm/AnonymousOverflow#25]
Instance URL: https://overflow.projectsegfau.lt
Region (Written Out - ex United States): Luxembourg/United States/India (GeoDNS)
Operated by (Link to your site): https://projectsegfau.lt/team

**Comment by gi-yt** [comment]
http://overflow.pjsfkvpxlinjamtawaksbnnaqs2fc2mtvmozrzckxh7f3kis6yea25ad.onion/ We also have a tor instance.

**Comment by httpjamesm** [comment]
Thanks for hosting an instance! It has been added to the README.
