### ISSUE TITLE
APP_URL doesn't seem to follow routes

### ISSUE THREAD

**Issue by StandingPadAnimations** [httpjamesm/AnonymousOverflow#28]
# What's Happening?
The `APP_URL` environment variable doesn't seem to take into account routes. For example, if I do `http://127.0.0.1/anonymousoverflow` and set up a proxy pass with Nginx, content like images doesn't load. This is annoying for Nginx setups like mine which use subdomains to handle different services.

## How to reproduce:
1. Clone the repo
2. Set `APP_URL` in `docker-compose.yml` to any domain + a route

## Affected Platforms:

- [ ] macOS
- [ ] Windows
- [x] Linux (Server is DietPi, laptop is Arch)
- [ ] iOS
- [x] Android

Version: 
1.8.1 
## Browser:
Librewolf on Arch, Mull on Android
- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [x] Gecko-based (ex: Firefox)

**Comment by httpjamesm** [comment]
Hey, thanks for reporting. 

I don't see where this issue can occur. All image proxy URLs are prefixed with the APP_URL environment variable, so it should work. Are you sure the issue is with the proxy URL and not an issue with your reverse proxy configuration?

**Comment by StandingPadAnimations** [comment]
My proxy config consists of the following:
```sh
location /anonymousoverflow/ {
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_pass http://127.0.0.1:8000/;
}
```
