### ISSUE TITLE
Light Theme Not Working Properly

### ISSUE THREAD

**Issue by jollySleeper** [httpjamesm/AnonymousOverflow#31]
Please make sure you're on the latest version before submitting.

# What's Happening?
Even if I have a Cookie set as "theme" = "light". Still AO opens up in Dark Mode even if the Cookie is Read.

## How to reproduce:
Have a Cookie set as "theme" = "dark" then manually edit it to "light". and refresh the page.

## Affected Platforms:

- [ ] macOS
- [ ] Windows
- [x] Linux (Fedora 37)
- [ ] iOS
- [ ] Android

Version: GNU/Linux Kernel 6.2

## Browser:

- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [x] Gecko-based (ex: LibreWolf)

**Comment by httpjamesm** [comment]
Hey, which instance is this? It sounds like an instance-specific CDN cache issue.

**Comment by xbdmHQ** [comment]
> Please make sure you're on the latest version before submitting.
> 
> # What's Happening?
> Even if I have a Cookie set as "theme" = "light". Still AO opens up in Dark Mode even if the Cookie is Read.
> 
> ## How to reproduce:
> Have a Cookie set as "theme" = "dark" then manually edit it to "light". and refresh the page.
> 
> ## Affected Platforms:
> * [ ]  macOS
> * [ ]  Windows
> * [x]  Linux (Fedora 37)
> * [ ]  iOS
> * [ ]  Android
> 
> Version: GNU/Linux Kernel 6.2
> 
> ## Browser:
> * [ ]  Chromium-based (ex: Brave or Chrome)
> * [ ]  Webkit-based (ex: Safari)
> * [x]  Gecko-based (ex: LibreWolf)

code.xbdm.fun (I fixed the issue on mines, dark/light mode is now working.)
overflow.fascinated.cc (This instance has cache problem too, someone needs to contact him to fix it.)

**Comment by Kuchteq** [comment]
Perhaps system theme mode could be added for distinguishing user's colorscheme preference via css's prefers-color-scheme?

**Comment by SudoVanilla** [comment]
I'm also using LibreWolf on Fedora 38 and can confirm this happens.
This appears to happen on my instance as well.
