### ISSUE TITLE
LaTeX rendering not implemented

### ISSUE THREAD

**Issue by njmdietrich** [httpjamesm/AnonymousOverflow#38]
Please make sure you're on the latest version before submitting.

# What's Happening?

This project is really nice, I love the cleanness of the website. However, there doesn't appear to be any LaTeX rendering. Without it, some posts are not very readable.

## How to reproduce:

Go to any Stackoverflow or Stackexchange post containing LaTeX, such as https://crypto.stackexchange.com/questions/68663/can-we-use-fixed-beavers-multiplication-triples-many-times

## Affected Platforms:

- [ ] macOS
- [ ] Windows
- [ ] Linux (Specify)
- [ ] iOS
- [ ] Android

Version: 

## Browser:

- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [ ] Gecko-based (ex: Firefox)

**Comment by njmdietrich** [comment]
Yes, that is exactly what I am talking about.

**Comment by httpjamesm** [comment]
I've experimented with this a bit and it's very tricky to do right. There are few robust libraries for server side rendering LaTeX. We may have to do this client side with JavaScript.

**Comment by shellheim** [comment]
This is the only gripe I have with anonymous overflow.
