### ISSUE TITLE
Consider adding an option to adjust parent max-width

### ISSUE THREAD

**Issue by extremelyonline** [httpjamesm/AnonymousOverflow#45]
Currently, the parent/wrapper can be quite wide.

This is a stylistic preference, but a long [line length](https://practicaltypography.com/line-length.html) also affects readability.

I suggest to add an option to adjust the max-width or a "center mode" that can be toggled on the server side. Thanks.

For instance, the css code can be:

```
@media (orientation: landscape) { 
.parent {
    max-width: 50%;
    width: fit-content;
}
}
@media (orientation: portrait) { 
.parent {
    max-width: 90%;
    width: fit-content;
}
}
```

**Comment by httpjamesm** [comment]
This has been added in version 1.9.0. Thank you for your input.

**Comment by McSinyx** [comment]
Max width of 50% can waste, well, (over, because padding) 50% of the screen estate.  I'd recommend targeting the line length directly like on the home page instead.
