### ISSUE TITLE
https://www.stackoverflow.com/a/UID URLs aren't redirected

### ISSUE THREAD

**Issue by gi-yt** [httpjamesm/AnonymousOverflow#47]
Please make sure you're on the latest version before submitting.

# What's Happening?
In many places like search engines, shortened stackoverflow URLs (Eg. https://www.stackoverflow.com/a/44390289) just redirect you to the homepage

## How to reproduce:
Go to https://www.stackoverflow.com/a/44390289

Version: 1.8.3

**Comment by httpjamesm** [comment]
This has been added in version 1.9.0. Thank you for your input.
