### ISSUE TITLE
Syntax-highlighting for code snippets

### ISSUE THREAD

**Issue by Bnyro** [httpjamesm/AnonymousOverflow#5]
Good evening,
currently the code snippets are only displayed as plain text, without any syntax highlighting. Support for syntax highlighting would make it easier to quickly get the fundamentals of the provided code by the responder. 

There are some JS libraries such as https://github.com/highlightjs/highlight.js that can deal with it, but since the app is currently using Go templates and thus SSR it's probably not the best way to solve it, apart from that you may want the app stay free of JavaScript. I've no clue whether there's any Go solution for it, but if so it would be the better one.

Cheers and thanks for the efforts, hope to see it being used more soon :)

**Comment by httpjamesm** [comment]
Thanks for your suggestion. It has been implemented in [version 1.2](https://github.com/httpjamesm/AnonymousOverflow/releases/tag/v1.2).

**Comment by Bnyro** [comment]
Awesome, thank you! :)

**Comment by BrightDV** [comment]
Hello,
I am not able to see any syntax-highlighting for code snippets. Has it been removed?
I tried on two Chromium browsers without success, while it works well on Chroma's playground.
<img src="https://user-images.githubusercontent.com/92821484/216676869-f90ed6c0-a4ae-4927-9825-05f19478e80f.png" height="400">

**Comment by BrightDV** [comment]
No, I specified the language. Without it, there wasn't any syntax highlighting…

**Comment by httpjamesm** [comment]
Well, there's your answer :)

The auto engine unfortunately isn't super sensitive, but it does work sometimes. It really depends on how much context has been given to the highlighter.

**Comment by BrightDV** [comment]
Ok, thanks for the precision!

**Comment by jpsnyder** [comment]
It seems like this is never working.

For example  https://code.whatever.social/questions/54026421/dynamically-add-a-column-to-datatables
has no highlighting even though stackoverflow detects and highlights just fine. 

Looking at their source, it looks like they do things like add `lang-js` or `lang-html` as a class on the `<pre>` tag. Could AnonymousOverflow, use that to determine language?


```html
<pre class="snippet-code-js lang-js prettyprint-override"><code>function Person( firstname, lastname, age ) {
    this._firstname = firstname;
    this._lastname  = lastname;
    this._age       = age;
 
    this.firstname = function () {
        return this._firstname;
    };

    this.lastname = function () {
        return this._lastname;
        ...
</code></pre>
```

**Comment by domeniczz** [comment]
> Syntax highlighting is still working, but it requires very obvious language markers to confidently detect the correct one. Did you set it to auto in the playground?

What do you mean by "set it to auto in the playground"? Is "playground" a settings page? I don't find it.
