### ISSUE TITLE
Links like /a/${question}/${answer} improperly redirected

### ISSUE THREAD

**Issue by banaanihillo** [httpjamesm/AnonymousOverflow#72]
[X] Please make sure you're on the latest version before submitting.

# What's Happening?

Expected https://stackoverflow.com/a/36667242/1128668 to redirect to the question with the identifier of 36667242 but it instead redirected to an unrelated question with the identifier of 1128668

## How to reproduce:

Follow a link onto a specific answer, i.e. with the question identifier first and then another identifier (for the answer) after it
Expectation: taken to https://overflow.datura.network/questions/36667242/placeholder
Reality: taken to https://overflow.lunar.icu/questions/1128668/placeholder

## Affected Platforms:

- [ ] macOS
- [ ] Windows
- [X] Linux (Specify) Ubuntu GNU/Linux 22.04 with GNOME 42.9 and X11
- [ ] iOS
- [ ] Android

Version: 
[unknown; I do not self host, I just use public instances]

## Browser:

- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [X] Gecko-based (ex: Firefox)

**Comment by banaanihillo** [comment]
Oh, I think I forgot where I am, I think I was supposed to add this issue onto LibRedirect and not here?

**Comment by banaanihillo** [comment]
No, wait, I actually don't know which end this issue belongs to. I'll keep this open open as well in case anyone happens to know.
https://codeberg.org/LibRedirect/browser_extension/issues/114

**Comment by httpjamesm** [comment]
This is actually an AO issue, as it doesn't know what to do with the extra /answer portion of the URL.

**Comment by httpjamesm** [comment]
Update: this was fixed a long time ago. The instances referenced are on ancient versions.
