### ISSUE TITLE
For  [duplicate] question, the layout of "This question already has answers here:" section is not correct

### ISSUE THREAD

**Issue by freedit-dev** [httpjamesm/AnonymousOverflow#78]
Just see https://overflow.freedit.eu/questions/59969183/global-immutable-hashset

![Screenshot](https://github.com/httpjamesm/AnonymousOverflow/assets/107944572/a9fb261a-e74f-44ba-b5eb-ff078361f3f6)

**Comment by httpjamesm** [comment]
Looks like we'll have to include some styling for the inline classes
![image](https://github.com/httpjamesm/AnonymousOverflow/assets/51917118/88294347-3390-4424-baf3-3c3f19978043)
