### ISSUE TITLE
Seeing "Error: Received a non-OK status code"

### ISSUE THREAD

**Issue by SudoVanilla** [httpjamesm/AnonymousOverflow#81]
![image](https://github.com/httpjamesm/AnonymousOverflow/assets/51213244/ed4d67a7-86ff-415e-80fc-7d22df29ad4a)

On my instance, I'm getting an error, not sure what the issue is.

https://overflow.sudovanilla.com/

**Comment by httpjamesm** [comment]
It suggests your instance is blocked

**Comment by 0x09AF** [comment]
There was a similar problem with libReddit, the solution was to attach cloudflare WARP tunnel to obfuscate the IP address.
I got my private AnonymousOverflow instance blocked for some reason, no one used it but me. Is there a way to unblock it or a timeout I need to wait?

**Comment by httpjamesm** [comment]
I wonder if a browser user agent needs to be provided to prevent blockage. The weird thing is this issue isn't very widespread. The official instance has a pretty high hourly request count, but it's still working just fine.

**Comment by httpjamesm** [comment]
https://github.com/httpjamesm/AnonymousOverflow/discussions/87
