### ISSUE TITLE
Redirect further SE links opened from within instance

### ISSUE THREAD

**Issue by opusforlife2** [httpjamesm/AnonymousOverflow#84]
## What's Happening?

Once you've opened an AO page, any further SE links end up taking you to the original SE website.

Like Libreddit/Redlib, AO should overwrite SE links within the opened page to that same AO instance.

## How to reproduce:

1. Open an AO page with an SE link in the question/answers.
2. Click on that link.

## Affected Platforms:

- [x] all

Version: Don't know how to check. This should be made visible somewhere on every instance page. e.g. Libreddit/Redlib shows version at the bottom of the page.

## Browser:

- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [x] Gecko-based (ex: Firefox)

**Comment by httpjamesm** [comment]
Versions can be found at the instance homepage.

This seems trivial to do - should only be some regex magic.
