### ISSUE TITLE
Getting redirected to seemingly random questions?

### ISSUE THREAD

**Issue by Wave6677** [httpjamesm/AnonymousOverflow#93]
Please make sure you're on the latest version before submitting.
1.11.0

# What's Happening?

When I open a link for StackExchange, Anonymous overflow shows me a completely different question that the one the link is for

## How to reproduce:

Search for a question that will show StackExchange results
Click the link

## Affected Platforms:

- [ ] macOS
- [ ] Windows
- [Fedora ] Linux (Specify)
- [ ] iOS
- [ ] Android

Version: 

## Browser:

- [ ] Chromium-based (ex: Brave or Chrome)
- [ ] Webkit-based (ex: Safari)
- [ X] Gecko-based (ex: Firefox)

Here's an example

https://superuser.com/questions/1698539/use-usb-tethering-for-local-router-as-internet-gateway 
redirects to 
https://code.whatever.social/questions/1698539/use-usb-tethering-for-local-router-as-internet-gateway
which is something about a WatiN error

**Comment by httpjamesm** [comment]
Please fill out the report template to the best of your ability. The version is needed to understand the context of your issue 🙂


You also didn't provide an example, which makes this impossible to debug.

**Comment by Wave6677** [comment]
> Please fill out the report template to the best of your ability. The version is needed to understand the context of your issue 🙂
> 
> You also didn't provide an example, which makes this impossible to debug.

So sorry, I hit submit too early while I was filling it out. You are FAST because I was going back to edit it and I hadn't even copied the second link I pasted before I noticed you responded haha

**Comment by httpjamesm** [comment]
Thanks for the additional details.

AnonymousOverflow doesn't officially support sites like Superuser. We've an ongoing discussion at #17.

![image](https://github.com/httpjamesm/AnonymousOverflow/assets/51917118/aa810faa-5edf-41c3-8133-a9037274b961)

**Comment by Wave6677** [comment]
Oh ok, cool. I'll close this then :P
